from app.routes.auth_routes import auth_bp
from app.routes.patient_routes import patient_bp
from app.routes.equipment_routes import equipment_bp
from app.routes.intervention_routes import intervention_bp
from app.routes.medical_record_routes import medical_record_bp
from app.routes.invoice_routes import invoice_bp
from app.routes.service_routes import service_bp
from app.routes.equipment_rental_routes import rental_bp
from app.routes.dashboard_routes import dashboard_bp