"""Add patient, equipment and intervention models

Revision ID: 636cd96a786e
Revises: fbc85e1aae75
Create Date: 2025-04-23 15:59:17.568501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636cd96a786e'
down_revision = 'fbc85e1aae75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('cin', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('poids', sa.Float(), nullable=True),
    sa.Column('taille', sa.Float(), nullable=True),
    sa.Column('imc', sa.Float(), nullable=True),
    sa.Column('tension_arterielle', sa.String(length=20), nullable=True),
    sa.Column('frequence_cardiaque', sa.Integer(), nullable=True),
    sa.Column('niveau_oxygene', sa.Float(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cin')
    )
    op.create_table('equipements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('modele', sa.String(length=100), nullable=False),
    sa.Column('numero_serie', sa.String(length=50), nullable=False),
    sa.Column('date_acquisition', sa.Date(), nullable=False),
    sa.Column('etat', sa.String(length=20), nullable=False),
    sa.Column('derniere_maintenance', sa.Date(), nullable=True),
    sa.Column('parametres', sa.JSON(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('date_attribution', sa.Date(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('equipement_id', sa.Integer(), nullable=False),
    sa.Column('technicien_id', sa.Integer(), nullable=False),
    sa.Column('date_intervention', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('rapport', sa.Text(), nullable=True),
    sa.Column('signature_patient', sa.Text(), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipement_id'], ['equipements.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['technicien_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interventions')
    op.drop_table('equipements')
    op.drop_table('patients')
    # ### end Alembic commands ###
